### PR TITLE
Detect non cli calls and add basic html formatting

### PR DESCRIPTION
**Pull request by DummerJunge**
Hello, 

because I want to give users without shell access the opportunity to update the fritz!box. So I added a basic detection for non cli calls  and some - NON STANDARD COMPLIANT - html formatting.

### CODE REVIEW

**Comment by jens-maus** [comment]
I am sorry, but what is your PR all about? I don't really get why you want to use carddav2fb in non-cli mode? What is the use case of that?

**Comment by DummerJunge** [comment]
Hallo, um Benutzern ohne ssh-Zugang die Aktualisierung zu erlauben, vielleicht zu speziell.

**Comment by jens-maus** [comment]
If you would provide a whole and complete web interface for that purpose I would understand and support it, but just enabling to call that php stuff from a webserver using a fake html header doesn't really help IMHO.

**Comment by DummerJunge** [comment]
Correct, unfortunately I do not have the php knowledge for this.

**Pull request closed without merging**
