### PR TITLE
Support Docker

### PR DESCRIPTION
**Pull request by nafets227**
I created a DockerFile and updated the Docs, maybe you want to include it into your base.

The docker Image is available on docker hub as nafets227/carddav2fb.

I am available for any kind of questions you might have...

### CODE REVIEW

**Comment by abma** [comment]
why did you copy config.example.php to config.example-docker.php?

IMHO config.example-docker.php should be deleted.

**Comment by carlos22** [comment]
@abma yes this seems strange...

**Comment by nafets227** [comment]
sorrry, I lost your comments and just re-found them now. Actually you are right. config-example-docker.php can be deleted. I will do it next days plus merge your latest changes plus optmize the docker Container for have the config file in a separate Directory /etc/carddav2fb

**Comment by nafets227** [comment]
Now I have a better Version uploaded to nafets227/carddav2fb. May I ask you to check again and Merge if ist ok or let me know?

**Comment by happyreacer** [comment]
how can the script in docker run? normaly i use a cron but i don't know how it works in the running docker container.

**Comment by nafets227** [comment]
I use Kubernetes and run the Container via Kubernetes CronJob.
This way a Container is started every hour in my case, inside the Container carddav is doing one sync and then it ends and the Container is finished and deleted.

**Pull request closed without merging**
